import './globals.css'
import type { Metadata } from 'next'
import { Roboto, Inter } from 'next/font/google'
import Nav from './components/Nav';
import { getServerSession } from 'next-auth/next';
import Hydrate from './components/Hydrate';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { motion } from 'framer-motion'

const inter = Inter({ subsets: ['latin'] })

const roboto  = Roboto({weight: ['400', '500', '700'], subsets:['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const session = await getServerSession(authOptions)
  // console.log(session)
  return (
    <html lang="en">
      <body
       className= {`bg-slate-900 mx-6 mt-5 text-slate-400 ${roboto.className}`}>
        <Hydrate>
        <Nav user={session?.user} expires={session?.expires as string}/>
        {children}
        </Hydrate>
        
        </body>
    </html>
  )
}
